### ISSUE TITLE
Settings menu

### ISSUE THREAD

**Issue by ilcardella** [yorickvanzweeden/Ubuntu-NordVPN-Indicator#2]
Hi, I am working on creating the Settings menu. I have pushed the branch on my fork if you want to try.
At the moment I have done a simple submenu, but I have just realised that the "Auto connect" and "DNS" settings may require additional fields such as Country, server, IP address, etc.
I think the best solution would be to have the "Settings..." label in the gtk menu which would open a separate window where we can handle all the UI widget better to expose all the possible configuration.
Let me know if you have better ideas

**Comment by yorickvanzweeden** [comment]
That seems perfect! :+1: 

Furthermore, I would distinguish between auto connect (let NordVPN figure it out) and connect favorite (user-specified location).

**Comment by ilcardella** [comment]
#### Problem
The current Setting window is not the best from an UI point of view and it does not acknowledge the output of the `Apply` action. A setting change might fail and the user would not see that.

#### Solution
I am planning on changing the window layout and how settings can be set in order to be more scalable in case of further changes of the client app.

The idea is:
- Have a section of the window to display the current settings
- Have a `help` button beside each single setting which return the `--help` message related with the setting
- Add a text area beside each single setting where the user can insert a new setting command:
  - i.e. Protocol: UDP - | help button | set protocol: | text area | | apply button |
  - in the text area the user would insert `UDP` or `TCP`, based on the help button output and then click on the `apply` button
  - in case of the `auto-connect` setting, the user would insert `on` or `enable` or `uk01` or anything valid
- At the bottom of the window, reserve an area to display:
  - the output of the `help` buttons
  - the output of the `apply` buttons

#### Pro
The indicator becomes agnostic of what settings are supported and what are not. In case of changes of settings in the client app, no further actions are required for the indicator.

#### Cons
It might look a bit less user friendly
